apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount-rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - keda-http.yaml
  - frontend.yaml
  - data-services.yaml
  - worker.yaml
  - workspace-pvc.yaml
